啤酒:
  material:
    料理用飲用水: 6
    發酵劑: 2
    砂糖: 1
    蕎麥: 5
  special: 清涼生啤酒
奧迪爾利塔套餐:
  box:
  - 道人
  - 15
  material:
    戴羅提亞布丁: 1
    戴羅提亞果汁: 2
    炒雞肉: 2
    蕨菜炒肉: 1
    雞胸肉沙拉: 2
  special: 特製奧迪爾利塔套餐
  support: True
巴洛斯便當:
  box:
  - 道人
  - 27
  material:
    柚子果汁: 2
    柚子糖: 2
    艾亦爾三明治: 2
巴雷諾斯套餐:
  box:
  - 道人
  - 24
  material:
    啤酒: 2
    炒青菜: 2
    煙燻魚排: 1
    肉丸子: 1
    起司焗烤: 1
  special: 特製巴雷諾斯套餐
戴羅提亞布丁:
  box:
  - 名匠
  - 18
  material:
    燕麥片: 1
    特等戴羅提亞: 1
    犀牛血: 7
    純水: 3
    蜂蜜酒: 2
  special: 戴羅提亞血色布丁
戴羅提亞果汁:
  material:
    特等戴羅提亞: 1
    砂糖: 3
    純水: 3
    草莓: 5
  special: 清涼的戴羅提亞果汁
柚子果汁:
  material:
    料理用飲用水: 5
    特等柚子: 1
    砂糖: 3
    食用蜂蜜: 1
  special: 甜蜜的柚子果汁
柚子糖:
  material:
    柚子: 1
    食用蜂蜜: 1
    黑糖: 1
  special: 酸甜的柚子糖
炒雞肉:
  material:
    橄欖油: 2
    特等洋蔥: 1
    蕎麥: 5
    雞肉: 5
  special: 香香的炒雞肉
炒青菜:
  material:
    橄欖油: 2
    特等辣椒: 1
    甜椒: 5
    鹽: 1
  special: 清脆的炒青菜
烤香腸:
  material:
    洋蔥: 1
    胡椒: 2
    鹽: 2
    鹿肉: 6
  special: 煙燻香腸
煙燻魚排:
  material:
    橄欖油: 1
    飛魚乾: 1
    鹽: 2
  special: 特製煙燻魚排
燕麥片:
  material:
    牛奶: 3
    特等洋蔥: 1
    蕎麥粉: 9
    食用蜂蜜: 2
  special: 精製的燕麥片
肉丸子:
  box:
  - 名匠
  - 18
  material:
    油炸用油: 3
    蕎麥粉: 5
    起司: 2
    雞蛋: 2
    鹿肉: 8
  special: 酥脆肉丸子
艾亦爾三明治:
  material:
    特等柚子: 1
    甜椒: 5
    雞蛋: 4
    鬆軟的麵包: 2
  special: 高級艾亦爾三明治
蕨菜炒肉:
  box:
  - 名匠
  - 18
  material:
    料理用飲用水: 5
    橄欖油: 2
    特等蒜頭: 1
    蕨菜: 3
    鹿肉: 6
  special: 清淡的蕨菜炒肉
蜂蜜酒:
  material:
    料理用飲用水: 6
    砂糖: 2
    酒的精髓: 2
    食用蜂蜜: 3
  special: 刺激的蜂蜜酒
起司焗烤:
  box:
  - 名匠
  - 18
  material:
    烤香腸: 1
    甜椒: 4
    紅醬: 3
    蕎麥粉麵團: 5
    起司: 3
  special: 有嚼勁的起司焗烤
酒的精髓:
  material:
    發酵劑: 1
    草莓: 1
    蕎麥粉: 1
醃製蔬菜:
  box:
  - 專家
  - 18
  material:
    甜椒: 8
    發酵劑: 2
    砂糖: 2
    醋: 4
  special: 糖醋醃蔬菜
醋:
  material:
    甜椒: 1
    發酵劑: 1
    砂糖: 1
    草莓: 1
雞胸肉沙拉:
  material:
    料理用紅酒: 2
    甜椒: 5
    草莓: 5
    醋: 1
    雞肉: 5
  special: 新鮮的雞胸肉沙拉
鬆軟的麵包:
  material:
    牛奶: 3
    發酵劑: 2
    蕎麥粉麵團: 6
    雞蛋: 4
  special: 濕潤的牛奶麵包

