啤酒:
  material:
    料理用飲用水: 6
    發酵劑: 2
    砂糖: 1
    蕎麥: 5
  special: 清涼生啤酒
奧迪爾利塔套餐:
  box:
  - 道人
  - 15
  material:
    戴羅提亞布丁: 1
    戴羅提亞果汁: 2
    炒雞肉: 2
    蕨菜炒肉: 1
    雞胸肉沙拉: 2
  special: 特製奧迪爾利塔套餐
  support: True
巴洛斯便當:
  box:
  - 道人
  - 27
  material:
    柚子果汁: 2
    柚子糖: 2
    艾亦爾三明治: 2
  support: True
巴雷諾斯套餐:
  box:
  - 道人
  - 24
  material:
    啤酒: 2
    炒青菜: 2
    煙燻魚排: 1
    肉丸子: 1
    起司焗烤: 1
  special: 特製巴雷諾斯套餐
  support: True
戴羅提亞布丁:
  box:
  - 名匠
  - 18
  material:
    燕麥片: 1
    特等戴羅提亞: 1
    犀牛血: 7
    純水: 3
    蜂蜜酒: 2
  special: 戴羅提亞血色布丁
戴羅提亞果汁:
  material:
    特等戴羅提亞: 1
    砂糖: 3
    純水: 3
    草莓: 5
  special: 清涼的戴羅提亞果汁
柚子果汁:
  material:
    料理用飲用水: 5
    特等柚子: 1
    砂糖: 3
    食用蜂蜜: 1
  special: 甜蜜的柚子果汁
柚子糖:
  material:
    柚子: 1
    食用蜂蜜: 1
    黑糖: 1
  special: 酸甜的柚子糖
炒雞肉:
  material:
    橄欖油: 2
    特等洋蔥: 1
    蕎麥: 5
    雞肉: 5
  special: 香香的炒雞肉
炒青菜:
  material:
    橄欖油: 2
    特等辣椒: 1
    甜椒: 5
    鹽: 1
  special: 清脆的炒青菜
烤香腸:
  material:
    洋蔥: 1
    特等胡椒: 1
    鹽: 2
    狼肉: 6
  special: 煙燻香腸
煙燻魚排:
  material:
    橄欖油: 1
    飛魚乾: 1
    鹽: 2
  special: 特製煙燻魚排
燕麥片:
  material:
    牛奶: 3
    特等洋蔥: 1
    蕎麥粉: 9
    食用蜂蜜: 2
  special: 精製的燕麥片
肉丸子:
  box:
  - 名匠
  - 18
  material:
    油炸用油: 3
    蕎麥粉: 5
    起司: 2
    雞蛋: 2
    狼肉: 8
  special: 酥脆肉丸子
艾亦爾三明治:
  material:
    特等柚子: 1
    甜椒: 5
    雞蛋: 4
    鬆軟的麵包: 2
  special: 高級艾亦爾三明治
蕨菜炒肉:
  box:
  - 名匠
  - 18
  material:
    料理用飲用水: 5
    橄欖油: 2
    特等蒜頭: 1
    蕨菜: 3
    狼肉: 6
  special: 清淡的蕨菜炒肉
蜂蜜酒:
  material:
    料理用飲用水: 6
    砂糖: 2
    酒的精髓: 2
    食用蜂蜜: 3
  special: 刺激的蜂蜜酒
起司焗烤:
  box:
  - 名匠
  - 18
  material:
    烤香腸: 1
    甜椒: 4
    紅醬: 3
    蕎麥粉麵團: 5
    起司: 3
  special: 有嚼勁的起司焗烤
紅醬:
  material:
    基本醬料: 1
    狼肉: 1
    料理用飲用水: 2
    砂糖: 2
酒的精髓:
  material:
    發酵劑: 1
    草莓: 1
    蕎麥粉: 1
醃製蔬菜:
  box:
  - 專家
  - 18
  material:
    甜椒: 8
    發酵劑: 2
    砂糖: 2
    醋: 4
  special: 糖醋醃蔬菜
  support: True
醋:
  material:
    甜椒: 1
    發酵劑: 1
    砂糖: 1
    草莓: 1
雞胸肉沙拉:
  material:
    料理用紅酒: 2
    甜椒: 5
    草莓: 5
    醋: 1
    雞肉: 5
  special: 新鮮的雞胸肉沙拉
鬆軟的麵包:
  material:
    牛奶: 3
    發酵劑: 2
    蕎麥粉麵團: 6
    雞蛋: 4
  special: 濕潤的牛奶麵包
艾亦爾特產品特餐:
  support: True
  material:
    柚子酒: 2
    雞油菇粥: 2
    柚子醃洋蔥: 1
    雞油菇湯: 1
  box:
  - 道人
  - 39
柚子酒:
  material:
    特等柚子: 1
    酒的精髓: 3
    砂糖: 1
    發酵劑: 3
  special: 酸甜的柚子酒
雞油菇粥:
  material:
    特等雞油菇: 1
    蕎麥: 5
    洋蔥: 1
    鹽: 2
    料理用飲用水: 3
  special: 香濃的雞油菇粥
柚子醃洋蔥:
  material:
    洋蔥: 2
    柚子醋: 2
    砂糖: 2
    發酵劑: 2
  special: 爽脆的柚子醃洋蔥
柚子醋:
  material:
    柚子: 2
    發酵劑: 1
    砂糖: 1
    料理用飲用水: 1
雞油菇湯:
  material:
    特等雞油菇: 1
    辣椒: 1
    紅醬: 1
    料理用飲用水: 2
  special: 微辣雞油菇湯
艾亦爾套餐:
  support: True
  material:
    雞油菇燉飯: 1
    雞油菇燉馬鈴薯: 1
    雞油菇炒肉: 1
    水果雪酪: 2
    桑黃菇馬格利酒: 2
  special: 特製艾亦爾套餐
  box:
  - 道人
  - 21
雞油菇燉飯:
  material:
    雞油菇: 2
    蕎麥: 5
    白醬: 1
    奶油: 1
    橄欖油: 1
  special: 香氣四溢的雞油菇燉飯
白醬:
  material:
    基本醬料: 1
    牛奶: 1
    草莓: 1
    料理用紅酒: 2
雞油菇燉馬鈴薯:
  material:
    雞油菇: 2
    馬鈴薯: 5
    洋蔥: 1
    甜椒: 2
    料理用飲用水: 5
  special: 營養滿滿的雞油菇燉馬鈴薯
雞油菇炒肉:
  material:
    特等雞油菇: 1
    豬肉: 5
    基本醬料: 2
    胡椒: 2
    鹽: 3
  special: 豐盛的雞油菇炒肉
  box:
  - 名匠
  - 18
水果雪酪:
  material:
    透明的冰塊: 1
    草莓: 2
    砂糖: 3
桑黃菇馬格利酒:
  material:
    桑黃菇: 2
    料理用飲用水: 3
    發酵劑: 3
    蕎麥: 5
  special: 柔和的桑黃菇馬格利酒
梅迪亞套餐:
  support: True
  material:
    暗黑布丁: 1
    燕麥片: 1
    烤香腸: 2
    瘦肉沙拉: 1
    異國的穀物酒: 2
  special: 特製梅迪亞套餐
  box:
  - 道人
  - 15
暗黑布丁:
  material:
    燕麥片: 1
    醃製蔬菜: 1
    雞肉: 5
    犀牛血: 7
  special: 血腥的暗黑布丁
  box:
  - 名匠
  - 15
瘦肉沙拉:
  material:
    狼肉: 1
    醋: 2
    特等胡椒: 1
    醬料: 4
  special: 高級的瘦肉沙拉
  box:
  - 名匠
  - 18
醬料:
  material:
    橄欖油: 1
    料理用飲用水: 1
    雞蛋: 1
    鹽: 2
異國的穀物酒:
  material:
    蕎麥粉麵團: 3
    酒的精髓: 1
    料理用飲用水: 5
    發酵劑: 2
  special: 釀熟的異國的穀物酒
  
